-- Run connected to ILPortal.
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS citext;
ALTER DATABASE "ILPortal" SET timezone TO 'UTC';
